### PR TITLE
Provide API for ignoring some multi-field updates

### LINKED ISSUE #57: multiFieldUpdate interacts poorly with dependent fields
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

The implementation of the multiFieldUpdate feature has surprising effects when multiple fields on the same block are dependent on one another. Consider something like App Inventor's ['math_number_radix' block](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/blocklyeditor/src/blocks/math.js#L50C16-L50C35). It has a radix dropdown field and a number text field.  When a radix value is changed the validator on the radix dropdown will cause a change to the number value (i.e. to conform to the new radix).  

If I have have multiple such blocks selected, potentially with different radix and number values, I would expect that changing the value of the radix on one block would just change all the blocks to have that radix, and that the number values on each block would change to match its proper value with the new radix, **and would be different for each block if the original values were different.**. However, with the current implementation all the blocks would end up with the same value.  I think (at least part of) the problem is that initiated changes (like the dropdown selection) need to be treated differently than the programmatic changes to dependent fields caused by the validator.

### Reproduction steps

1. 
2. 
3.

### Stack trace

_No response_

### Screenshots

_No response_

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by mark-friedman**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes #57

### Proposed Changes

Allows a user of the plugin to temporarily disable mult-ifield updates within a particular scope.

### Reason for Changes

Multi-field updates can cause issues with dependent fields on the same block.  See issue #57 anad the updated README file in this PR for some more details.

### Documentation

This PR includes additions to the README file.

### CODE REVIEW

**Comment by HollowMan6** [comment]
I have no strong objection against merging this PR, but here is a checklist before we do so to ensure everything is intended:
- [ ] If we set a new group instead of continuing with the old group, have you checked that this doesn't break the redo/undo (so that we still have both programmatically and multi-field updates reverted together)? AFAIK, we should always include those changes in the same group ID to get this working.
- [ ] This is a helper function that doesn't include any uses of the internals of the plugin, so I doubt if it's necessary to include this in the plugin instead of documenting this and the developer implementing this wapper at their side.

File: src/multiselect.js [hunk 1]
```diff
@@ -114,6 +114,21 @@ export class Multiselect {
...
+      const oldGroup = Blockly.Events.getGroup();
+      // Note that this depends on the fact that eventListener_ will ignore events with a group ID.
+      Blockly.Events.setGroup("ignoreMultiFieldUpdates");
+      try {
+          func();
+      } finally {
+        Blockly.Events.setGroup(oldGroup);
+      }
+  }
+
```
Comment (HollowMan6) [inline src/multiselect.js:131]: If the answer to my 2nd checklist question is yes, then I would recommend moving this to `src/index.js` and exporting the function alone instead, since it's a helper function and doesn't correlate to the plugin directly.

**Comment by mark-friedman** [comment]
@HollowMan6 While testing redo/undo I discovered something worse, which is that multi-field updates of input fields (like the "math _number" or "text" blocks) was broken!  That's because the events for those changes have group IDs set.  I'm guessing that that was added when Blockly added the "block_field_intermediate_change" event.  Given that, I think that we need to revert your change which added the `e.group === ''` test to `eventListener_`.   Unfortunately, it also mean that we'll have to disable the multi-field update option in App Inventor.

**Comment by mark-friedman** [comment]
Withdrawing this PR.  See https://github.com/mit-cml/workspace-multiselect/pull/61#issuecomment-2189527061 for why.

**Comment by HollowMan6** [comment]
Just pushed https://github.com/mit-cml/workspace-multiselect/commit/698fb5100abd5c91fac9155c475e119faad4e16d to fix the multi update under "block_field_intermediate_change" event. In this case, it looks like we just need to keep track of the group IDs for those events and make sure that either `e.group === ''`  or `e.group` is within the group IDs of intermediate changes, and there's no need to worry too much about this.

Also, although normally you can get the multi-field group ID by listening to events, to make developer's life easier, now I also expose the group ID through the `multiFieldUpdateGroupID` field. Now we can still wrap any dependent fields by saving any existing group id, set the group ID here, do our work, reset the group id (in the finally clause), just as mentioned in https://github.com/mit-cml/workspace-multiselect/issues/57#issuecomment-2175980296 and https://github.com/mit-cml/workspace-multiselect/commit/bd32cd1b0f052860a4b6f967cc7fd66e305f8b83#commitcomment-143269534)

**Comment by mark-friedman** [comment]
> Just pushed [698fb51](https://github.com/mit-cml/workspace-multiselect/commit/698fb5100abd5c91fac9155c475e119faad4e16d) to fix the multi update under "block_field_intermediate_change" event. In this case, it looks like we just need to keep track of the group IDs for those events and make sure that either `e.group === ''` or `e.group` is within the group IDs of intermediate changes

Ok, I'll test that out.

**Comment by mark-friedman** [comment]
> Ok, I'll test that out.

Looks good.  Ideally we would see the intermediate changes on the other fields as the user typed, but I think the current behavior is acceptable.

**Comment by mark-friedman** [comment]
> * If we set a new group instead of continuing with the old group, have you checked that this doesn't break the redo/undo (so that we still have both programmatically and multi-field updates reverted together)? AFAIK, we should always include those changes in the same group ID to get this working.

Good catch.  I have fixed that.

**Comment by mark-friedman** [comment]
>This is a helper function that doesn't include any uses of the internals of the plugin, so I doubt if it's necessary to include this in the plugin instead of documenting this and the developer implementing this wapper at their side.

I'm going to push back a little on this.  While it doesn't *use* the internals of the plugin, it does depend on those internals by knowing that the way to get the field's events ignored within `eventListener_` function is to set a group id.

>... now I also expose the group ID through the multiFieldUpdateGroupID field. Now we can still wrap any dependent fields by saving any existing group id, set the group ID here, do our work, reset the group id (in the finally clause)

I think that this approach creates a leaky abstraction.  It requires the user of the plugin to be aware of details of the underlying implementation.  That's why I created the `withoutMultiFieldUpdates` function in the plugin (and in the Multiselect class), so that if anything ever changes in the `eventListener_` function, we can update `withoutMultiFieldUpdates` and the user doesn't care.

File: src/multiselect.js [hunk 2]
```diff
@@ -116,6 +116,23 @@ export class Multiselect {
     }
   }
 
+  /**
+   * Ignore multi-field updates within the given function.
+   * @param {function} func The function to call.
+   */
+  withoutMultiFieldUpdates(func) {
```
Comment (HollowMan6) [inline src/multiselect.js:123]: Since this is just an event wrapper for a function, let's make the method name more general. I'm sure developers will find other use cases and it's not limited to `withoutMultiFieldUpdates`. What about the name `eventWrapper`?

File: src/multiselect.js [hunk 3]
```diff
@@ -116,6 +116,23 @@ export class Multiselect {
...
+    let oldGroup = Blockly.Events.getGroup();
+    // Note that this depends on the fact that eventListener_ will ignore events with a group ID.
+    if (!oldGroup) {
+      Blockly.Events.setGroup("ignoreMultiFieldUpdates");
```
Comment (HollowMan6) [inline src/multiselect.js:127]: Is it necessary to use a fixed group ID here? If yes, I would suggest we make the group ID one of the method parameters and pass it here, to make it more flexible. If no, let's simply use `Blockly.Events.setGroup(true);`

File: src/multiselect.js [hunk 4]
```diff
@@ -116,6 +116,23 @@ export class Multiselect {
...
+    }
+    try {
+        func();
+    } finally {
+      Blockly.Events.setGroup(oldGroup);
+    }
+  }
+
```
Comment (HollowMan6) [inline src/multiselect.js:135]: I would still recommend moving this to `src/index.js` and getting the function exported directly, since anyway we are not using any private methods or fields of the `MultiSelect` class, so this is more like a static method.

**Comment by HollowMan6** [comment]
> Looks good. Ideally we would see the intermediate changes on the other fields as the user typed, but I think the current behavior is acceptable.

I don't find any API for doing those intermediate changes, plus #58 applies as well if we want to have this, and this time, we have a random group ID. So, let's not complicate things further unless someone is interested in implementing this.

**Review by HollowMan6 — CHANGES_REQUESTED** [review]
> I think that this approach creates a leaky abstraction. It requires the user of the plugin to be aware of details of the underlying implementation. That's why I created the withoutMultiFieldUpdates function in the plugin (and in the Multiselect class), so that if anything ever changes in the eventListener_ function, we can update withoutMultiFieldUpdates and the user doesn't care.

Okay, fair enough. You can go ahead to remove the `multiFieldUpdateGroupID` field, which I introduced in my last commit. BTW, we also need to resolve the rebase conflicts to make this PR mergeable. Once we address all the issues, we can go ahead to merge this PR.

File: src/multiselect.js (hunk 2 above)
Comment (mark-friedman) [reply src/multiselect.js:123]: It's not really an event wrapper.  It's used to wrap code that sets dependent field updates.  And it is specifically designed to cause the multi-field updating to ignore those dependent field updates.  I'm not sure that I see any other use for it.  Given all that I think that the name is apt.

File: src/multiselect.js (hunk 4 above)
Comment (mark-friedman) [reply src/multiselect.js:134]: How about if I just make it static, then?  One reason why I'd like to keep it as part of the Multiselect class is for plugin users (like App Inventor) who don't load the plugin via an  ES6 `import`.  In those use cases the exported names are just added to the top-level, `window` object, and so in this case would just look something like `window.withoutMultiFieldUpdates` without any indication that is is related to the Multiselect plugin. Adding it to the `Multiselect` class makes that association clear.

File: src/multiselect.js (hunk 3 above)
Comment (HollowMan6) [reply src/multiselect.js:126]: If it's not neccessary to have a fixed group ID, then let's still use the random one to avoid any possible issues caused by ID collision. 

```suggestion
      Blockly.Events.setGroup(true);
```

Comment (mark-friedman) [reply src/multiselect.js]: Done.

**Comment by mark-friedman** [comment]
> > Looks good. Ideally we would see the intermediate changes on the other fields as the user typed, but I think the current behavior is acceptable.
> 
> I don't find any API for doing those intermediate changes, plus #58 applies as well if we want to have this, and this time, we have a random group ID. So, let's not complicate things further unless someone is interested in implementing this.

I think you would just need to change `e.type === Blockly.Events.CHANGE` to `e.type === Blockly.Events.CHANGE  || Blockly.Events.BLOCK_FIELD_INTERMEDIATE_CHANGE`  in the `eventListener_` function.

File: src/multiselect.js (hunk 2 above)
Comment (HollowMan6) [reply src/multiselect.js:122]: Actually, this method can be used more than just for ignoring those dependent field updates in multi-field updates. We also use a similar structure when we do our multi-field update: https://github.com/mit-cml/workspace-multiselect/blob/main/src/multiselect.js#L256-L290 (saving any existing group id, set the group ID here, do our work, reset the group id in the finally clause). And I think this can be generalized and useful when someone just wants to hook some actions and make sure that these actions can be redo/undo together with the previous ones. (e.g. possibily dragging/pasting blocks) 

Forgive me if I'm too picky on the names, We have to think carefully about the name at this stage, as we want to avoid breaking changes, it's always a bad idea to do API renaming if later we find it can have a better name.

File: src/multiselect.js (hunk 4 above)
Comment (HollowMan6) [reply src/multiselect.js]: Sounds good

File: src/multiselect.js (hunk 2 above)
Comment (mark-friedman) [reply src/multiselect.js:122]: I'm picky on names too.  

The fact that setting the group ID has the effect of ignoring the multi-field update is an implementation detail of the plugin.  If the implementation changed so that that was no longer the case we would change the `withoutMultiFieldUpdates` function (and it might not involve event group IDs at all). If users just want to cause undo/redo grouping, they would, presumably, already know to use `setGroup()`, since that is its intended use in Blockly.  That wouldn't be something that the Multiselect plugin would be expected to provide as a function.

Comment (HollowMan6) [reply src/multiselect.js]: > If the implementation changed so that that was no longer the case we would change the withoutMultiFieldUpdates function (and it might not involve event group IDs at all)

Ah yeah, we should definitely take this into account as well, then it's good to keep this name.

**Review by HollowMan6 — APPROVED** [review]
Now LGTM. I would like to merge this one now but the GitHub bug https://github.com/mit-cml/workspace-multiselect/pull/61#issuecomment-2192479167 stops me from doing so. Maybe we can open a new PR to supersede this one.

**Comment by mark-friedman** [comment]
> Now LGTM. I would like to merge this one now but the GitHub bug [#61 (comment)](https://github.com/mit-cml/workspace-multiselect/pull/61#issuecomment-2192479167) stops me from doing so. Maybe we can open a new PR to supersede this one.

It now seems to say "This branch has no conflicts with the base branch" so maybe we're ok.  If not, let me know and I'll create a new PR.

**Comment by HollowMan6** [comment]
> It now seems to say "This branch has no conflicts with the base branch" so maybe we're ok. If not, let me know and I'll create a new PR.

Not like that at my side. Actually I found the similar thing for Chang Min's newly opened PR, which makes this even stranger, so I'm not sure if it's more about a privilege issue or not. cc @ewpatton to see if he can merge the PR here.

image
image

**Comment by mark-friedman** [comment]
Further weirdness is that now my GitHub page for this PR says "This branch has conflicts that must be resolved" despite nothing in the code having changed since when I reported that it said there were no conflicts.

**Comment by mark-friedman** [comment]
And now it says "This branch has no conflicts with the base branch".  Very very weird.

**Comment by HollowMan6** [comment]
> I think you would just need to change `e.type === Blockly.Events.CHANGE` to `e.type === Blockly.Events.CHANGE || Blockly.Events.BLOCK_FIELD_INTERMEDIATE_CHANGE` in the `eventListener_` function.

> Further weirdness is that now my GitHub page for this PR says "This branch has conflicts that must be resolved" despite nothing in the code having changed since when I reported that it said there were no conflicts.

> And now it says "This branch has no conflicts with the base branch". Very very weird.

Ah, acutally I have just got this supported and pushed one commit into main, and I have helped you resolved the conflit, but still it shows "This branch cannot be rebased due to conflicts" at my side, even now your side seems to be normal. I'll open a ticket at GitHub support to find out what's going on

image

**Comment by mark-friedman** [comment]
I think we've got some bad merging happening.  The `eventListener_` function looks wrong now.  The existence and use of the `fieldIntermediateChangeGroupIds_` set is gone, the `finally` block has changed and the big conditional near the beginning is incorrect.

**Comment by HollowMan6** [comment]
Now I know what's going on, I just can't use rebase and merge here in this case since we have several merge commits in the commit history, so I'll use Squash and merge  to merge

image

**Comment by mark-friedman** [comment]
I think that this is what we want the `eventListener_` function to look like:
```js
  eventListener_(e) {
    if (e.type === Blockly.Events.BLOCK_FIELD_INTERMEDIATE_CHANGE) {
      // Keep track of the group ids for intermediate changes.
      this.fieldIntermediateChangeGroupIds_.add(e.group);
    // on Block field changed
    } else if (this.multiFieldUpdate_ &&
        (e.type === Blockly.Events.CHANGE || e.type === Blockly.Events.BLOCK_FIELD_INTERMEDIATE_CHANGE) &&
        e.element === 'field' && e.recordUndo &&
        this.blockSelection_.has(e.blockId) &&
        (e.group === '' ||
          this.fieldIntermediateChangeGroupIds_.has(e.group))) {
      const currentGroup = Blockly.Events.getGroup();
      if (e.group !== '' && e.group !== currentGroup) {
        // Intermediate changes are finished, remove the group id.
        this.fieldIntermediateChangeGroupIds_.delete(e.group);
      }
      const inGroup = !!currentGroup;
      if (!inGroup) {
        Blockly.Events.setGroup(true);
        e.group = Blockly.Events.getGroup();
      }
      try {
        const blockType = this.workspace_.getBlockById(e.blockId).type;
        // Update the fields to the same value for
        // the selected blocks with same type.
        this.blockSelection_.forEach((id) => {
          if (id === e.blockId) {
            return;
          }
          const block = this.workspace_.getBlockById(id);
          if (block.type === blockType) {
            block.setFieldValue(e.newValue, e.name);
          }
        });
      } catch (err) {
        // Avoid errors when changing a block if it is
        // no longer in the workspace.
        // https://github.com/mit-cml/workspace-multiselect/issues/33
        console.warn(err);
      } finally {
        if (!inGroup) {
          Blockly.Events.setGroup(false);
        } else {
          Blockly.Events.setGroup(currentGroup);
        }
      }
    }
  }
```

And we want the constructor to be:
```js
constructor(workspace) {
    this.workspace_ = workspace;
    this.origHandleWsStart_ = Blockly.Gesture.prototype.handleWsStart;

    blockSelectionWeakMap.set(this.workspace_, new Set());
    this.blockSelection_ = blockSelectionWeakMap.get(this.workspace_);
    inMultipleSelectionModeWeakMap.set(this.workspace_, false);
    BaseBlockDraggerWeakMap.set(this.workspace_, Blockly.BlockDragger);
    this.fieldIntermediateChangeGroupIds_ = new Set();
    this.useCopyPasteCrossTab_ = true;
    this.useCopyPasteMenu_ = true;
    this.multiFieldUpdate_ = true;
  }
```

**Comment by HollowMan6** [comment]
> I think we've got some bad merging happening. The `eventListener_` function looks wrong now. The existence and use of the `fieldIntermediateChangeGroupIds_` set is gone, the `finally` block has changed and the big conditional near the beginning is incorrect.

Yes, this is intended, we don't need fieldIntermediateChangeGroupIds_ any more now. The finally block is intended (we still have an empty group if we are not in a group, so these are intended

**Comment by mark-friedman** [comment]
> > I think we've got some bad merging happening. The `eventListener_` function looks wrong now. The existence and use of the `fieldIntermediateChangeGroupIds_` set is gone, the `finally` block has changed and the big conditional near the beginning is incorrect.
> 
> Yes, this is intended, we don't need fieldIntermediateChangeGroupIds_ any more now. The finally block is intended (we still have an empty group if we are not in a group, so these are intended

Oh, ok.  I think that the `if` statement still needs to be fixed, though.

**Comment by HollowMan6** [comment]
> I think that this is what we want the `eventListener_` function to look like:
> 

We don't have e.element field in Blockly.Events.BLOCK_FIELD_INTERMEDIATE_CHANGE, and e.recordUndo is false, so we don't check these for BLOCK_FIELD_INTERMEDIATE_CHANGE

**Comment by HollowMan6** [comment]
Anyway, there's nothing unintentional when I check https://github.com/mit-cml/workspace-multiselect/pull/61/files, so I'll just merge this one. If we do find anything for the if statement, then it's introduced in https://github.com/mit-cml/workspace-multiselect/commit/698fb5100abd5c91fac9155c475e119faad4e16d I'll merge this PR now.

**Comment by mark-friedman** [comment]
> > I think that this is what we want the `eventListener_` function to look like:
> 
> We don't have e.element field in Blockly.Events.BLOCK_FIELD_INTERMEDIATE_CHANGE, and e.recordUndo is false, so we don't check these for BLOCK_FIELD_INTERMEDIATE_CHANGE

Ah, ok.  Sorry for the panic.  That's the danger when multiple people are changing parts of the same code at the same time, and thinking that there were, perhaps, weird merge conflicts.
